# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-02 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=usuarios.models.user_image_location)),
                ('avatar_thumb', models.ImageField(blank=True, null=True, upload_to=usuarios.models.user_thumb_location)),
                ('localidad', models.CharField(blank=True, max_length=30, null=True)),
                ('comunidad', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=700, null=True)),
                ('pujas', models.ManyToManyField(blank=True, to='hct.Subasta')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
